apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backstage-router-http
  namespace: backstage
spec:
  entryPoints:
    - web # Directs Traefik to look at port 80
  routes:
    - match: Host(`backstage.local`)
      kind: Rule
      services:
        - name: backstage-service
          port: 7007
      middlewares:
        - name: redirect-to-https # Triggers the immediate 308 upgrade
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backstage-router-https
  namespace: backstage
spec:
  entryPoints:
    - websecure # Directs Traefik to look at port 443
  routes:
    - match: Host(`backstage.local`)
      kind: Rule
      services:
        - name: backstage-service
          port: 7007
  tls:
    secretName: backstage-tls-secret # Restores your cert-manager keys

