apiVersion: v1
kind: Secret
metadata:
  name: backstage-github-secrets
  namespace: backstage
type: Opaque
stringData:
  # stringData allows plain text input; Kubernetes encodes it to base64 automatically
  GITHUB_APP_ID: "1234567"
  GITHUB_APP_CLIENT_ID: "346b5e65w6b45wy65w6b"
  GITHUB_APP_CLIENT_SECRET: "546b4w6b45w6b45w645wm75w47m4e678e64m784e"
  GITHUB_APP_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAzd5z/mr/FK2Ztt7jswhd7QzfrU4z/HFOy0FtI/6LIAKwAxVQ
    IzUyhXBsdDhNpAPF4JRWiiiXuNYKbqCuIM7aPujycymFVYpGritdyUHOYY88uq2f
    lmZAs1cjteldrWDfYsMQKN7HnJn22uoo/PNvPe18Goc4a/ExBknm9ysOhdd/H7nm
    N61bW/clSHNmfO8iJ2wAnwblhgvKIMQKnDhX8m2PexwmwEOlU+DlkTr8xjNwOb3n
    Lcenefw89TAbLdDsngm7/y9EJ+ocuOwp0/VTZ2PURK121zt/oVRQX97qgI4bBkuF
    R8XQp54oQLiS/p4GE9xExb3JFpUOATPTVKkP/wIDAQABAoIBAFO4j7t7j9i88LIp
    2rfIQ0pP3fcAwqt6+Ow340asEbAm56WZWUm4LJ+PpMtuykRVNHesW7U75NfKU9vB
    hI7bEG5dFZw32n17CltyT2W1WVTbh3rzeN8VHmLQoTktemcz6iSj50J3tv28r2M/
    rwOPjEHG/546ne54n456n45645b6456456b45645654mDRTYNRTENYsrt56en8sw
    nZlItmi2+6nuquo2d8FuzimFjTyiSDvJPOEbg5FGfRgEynWXRZDvNzqRoSfcR6VN
    wCrz+selEIFsW1RNFVUQF/fZhmyHIhbiow0hQBK0AkFeJmcUpvubLJg+t21Q07b1
    2oxjnAECgYEA/S7SRHiQTVd7WMGT5jeIdkirdc2Le2AXvFamWceYId3obkO1u3Ws
    MixQjCu/lxm4G/1mFb7RYHDeqhyFYABfAsnkgkgM9N1eNDZCldgqdcnd+E00pQEQ
    uAEHxTxDVWtAyNxGl7T21q85tW1GTbD39cCBAiPReRlzBu3eqXqU/38CgYEA0Cjc
    QmzEWnhV8qtnM02vMYSDXxJjzp0tsNrBuZxa5wi/8uj/omrQS1AS1M1MdV30HeNs
    IvDIgu0zuEhqd5w8IcSTzMY5rCQI5Z0VLnfaVS98e6jQy/2BomAfPC8ofT4NSUT7
    4WVuJMWZTosOm8cHteE5mfglkCbbF6MW6CFUL4ECgYAM+/a6njhATyk7Pwo3t0df
    UZDBhN4PYLk25na3if3qVrgR15UdXQaMuCsVVTUJKb+AZ/lxSgzw1jkFHltUthAp
    U3NNnyZS9HtdUB8QEjrzOXwRvNvjTm+uEBd27QVC/zIeWvWf2B8EmY3rGQSO/XFq
    DDYTYDTdf678hsTRIKF&6545634AADFfg5352342689jB$B$&GHWSF6/WF7v93++
    ElzXRpxba0vU76ScFs2siruf3H9HIaCvlGsmJNTcvcT2FcuBHRP/fN+MpRhdMLaz
    dppJ8kcG1K1B3JFCqYAT6D1R4NyxDTvrgCmZt+ic9SAYXPUPlz733GeiTXQ6NLVW
    0k8ugQKBgQD3BIfvLcWPkTHA/Kdgo2YEYPsHgpC7i867hLCKKeSGbC+8Fd4pFpLG
    WdJeNN3g4m0ubeBjMSZbg9M7oP5wXK1zP+tSfuSD1LsAATcpBoVij5qUBQtXGcuR
    2hdj341H/SboGGLqEVfVDgYkm+QbaHFD49xNSkGpRRAgxRvJJn7CpA==
    -----END RSA PRIVATE KEY-----
